# workflow to run both yarn && yarn build in the repo when pr is merged to main
name: Publish Connectors

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    # checkout the repo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@chili-publish'
      - name: Install dependencies
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_SECRET }}
      - name: Download index.json
        uses: azure/CLI@v1
        with:
          inlineScript: |
            container_name="sdk"
            blob_name="connector-repo/index.json"
            destination_file="existing/index.json"
            connection_string="${{ secrets.AZURE_CDN_STUDIO_DEV_CONNECTION_STRING }}"

            # ensure 'existing' folder exists
            mkdir -p existing

            # Check if the blob exists
            blob_exists=$(az storage blob exists --name $blob_name --container-name $container_name --connection-string $connection_string --output tsv --query exists)

            # If the blob exists, download it
            if [ $blob_exists == "true" ]; then
                az storage blob download --name $blob_name --file $destination_file --container-name $container_name --connection-string $connection_string --no-progress
            else
                echo "Blob does not exist."
            fi
      - name: Build Cli
        run: yarn run build-cli
      - name: Build and Publish connectors
        run: node scripts/publish.js
      - name: copy to upload folder
        run: mkdir -p upload/connector-repo && cp -r publish/* upload/connector-repo
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: connectors
          path: upload/connector-repo
      - name: Upload to Azure
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch -d sdk -s upload/ --connection-string "${{ secrets.AZURE_CDN_STUDIO_DEV_CONNECTION_STRING }}" --overwrite true
